parent_cfg: configs/components/datasets/base_dataset.yaml
white_bkgd: False
dataset_cfg: &dataset_cfg
    data_root: 'zju-mocap'
    img_dir: 'images'
    img_frame_format: '{:06d}.jpg'
    msk_dir: 'schp' # masks for basketball
    msk_frame_format: '{:06d}.png'
    resize_ratio: 0.5
    crop_h_w: [-1, -1]
    input_view_sample: [0, 21, 2, -1]
    render_view_sample: [0, 21, 2, -1]
    test_views: [-1]
    preload_data: True
    imgs_per_batch: 8
    ignore_dist_k3: False
    bbox_type: 'NHR'
    shift_pixel: False
    near_far: [0.1, 100.]
train_dataset:
    <<: *dataset_cfg
    split: 'train'
    frame_sample: [0, 300, 1]
test_dataset:
    <<: *dataset_cfg
    split: 'test'
    frame_sample: [0, 300, 30]
    input_view_sample: [0, 21, 2, -1]
    render_view_sample: [1, 21, 2, -1]