exp_name: 'FILENAME'
evaluator_module: lib.evaluators.nerf
chunk_size: 4096
bound_padding: 0.1 # padding for bounding box
evaluate:
    save_with_alpha: True
    metrics: ['psnr', 'ssim', 'lpips']
    save_keys: ['rgb', 'depth']
save_result: False
fps: 15
bounds: [[-100., -100., -100.], [100., 100., 100.]]

# Im4D 3.3 efficient training
joint_iters: 2147483647 # 2**31-1
finetune_iters_per: 1