chunk_size: 65536 # 2**20
test_dataset:
    frame_sample: [0, 150, 1] #
    render_view_sample: [0, 60, 3, -1]
    test_views: [-1]
    preload_data: False
    resize_ratio: 0.5
    special_resize_ratio: 0.375
    crop_h_w: [960, 640]
evaluate:
    metrics: []
    save_keys: ['depth']
save_result: True
save_tag: pcd
depth_method: median