scene: 'sport_1_easymocap'
bounds: [[-0.3871598, -0.3356453, -0.15346932], [0.36616263, 1.0683727,  1.5910634]]
# align gravity
configs:
  - configs/components/datasets/nhr_dataset.yaml
  - configs/components/datasets/mvibr.yaml
  - configs/components/methods/im4d.yaml
  - configs/components/losses/kplanes_loss.yaml
  - configs/components/opts/base_opt.yaml
  - configs/components/opts/im4d_opt.yaml
  - configs/components/engine/im4d_engine.yaml

num_pixels: 3072
train:
    epoch: 120
dataset_cfg: &dataset_cfg
    transform: [[1., 0., 0., 0.], [0., 0.17364818, -0.98480775, -3.88852744], [0., 0.98480775, 0.17364818, 2.16014765], [0., 0., 0., 1.]]
network: 
    xyz_encoding:
        temporal_res: [100, 100, 100, 100]
train_dataset:
    <<: *dataset_cfg
test_dataset:
    <<: *dataset_cfg

sampler_cfg: &sampler_cfg
    N_anneal_slope: 10.
    N_anneal_steps: 1000

samplers:
    - type: cascade_sampler 
      num_samples: 32
      <<: *sampler_cfg
      only_geo: True
      xyz_encoding:
        type: kplanes
        in_dim: 4
        include_input: False
        spatial_res: [128]
        temporal_res: [100]
        num_feat_ch: 12
        res_composite: concat
        planes_composite: concat
      net:
        type: nerf
        width: 64
        depth: 1
        view_depth: 2
        view_width: 64
        activation: relu
        skips: [4,]
      dir_encoding:
        type: frequency
        in_dim: 3
        num_frequencies: 1
        include_input: True
    - type: uniform_sampler
      num_samples: 64