task: im4d
network_module: lib.networks.nerf.methods.mvibr
network: &network_cfg
    net:
        type: im4d
        width: 64
        depth: 1
        view_depth: 2
        view_width: 64
        activation: relu
        skips: [4,]
        only_geo: True
    xyz_encoding:
        type: im4d
        in_dim: 4
        include_input: False
        spatial_res: [64, 128, 256, 512]
        temporal_res: [150, 150, 150, 150]
        num_feat_ch: 16
        res_composite: concat
        planes_composite: concat
        feat_dim: 8
    dir_encoding:
        type: frequency
        in_dim: 3
        num_frequencies: 1
        include_input: True
    feature_net:
        type: enerf_unet
sampler_cfg: &sampler_cfg
    N_anneal_slope: 10.
    N_anneal_steps: 1000
samplers: 
    - type: cascade_sampler 
      num_samples: 32
      <<: *network_cfg
      <<: *sampler_cfg
      only_geo: True
      xyz_encoding:
        type: kplanes
        in_dim: 4
        include_input: False
        spatial_res: [128]
        temporal_res: [150]
        num_feat_ch: 12
        res_composite: concat
        planes_composite: concat
      net:
        type: nerf
        width: 64
        depth: 1
        view_depth: 2
        view_width: 64
        activation: relu
        skips: [4,]
    - type: uniform_sampler
      num_samples: 64