task: ngp
network_module: lib.networks.nerf.network
network: &network_cfg
    density_act: relu
    net:
        type: nerf
        width: 64
        depth: 1
        view_depth: 2
        view_width: 64
        activation: relu
        skips: [4,]
    xyz_encoding:
        type: tcnn
        otype: HashGrid
        in_dim: 3
        n_levels: 16
        n_features_per_level: 2
        log2_hashmap_size: 19
        base_resolution: 16
        per_level_scale: 1.38
        include_input: True
    dir_encoding:
        type: frequency
        in_dim: 3
        num_frequencies: 1
        include_input: True
sampler_cfg: &sampler_cfg
    N_anneal_slope: 10.
    N_anneal_steps: 1000
samplers: 
    - type: cascade_sampler 
      num_samples: 32
      <<: *network_cfg
      <<: *sampler_cfg
      only_geo: True
      xyz_encoding:
          type: tcnn
          otype: HashGrid
          in_dim: 3
          n_levels: 8
          n_features_per_level: 2
          log2_hashmap_size: 17
          base_resolution: 16
          per_level_scale: 1.38
          include_input: True
    - type: uniform_sampler
      num_samples: 64